### ISSUE TITLE
Custom Ubuntu won't boot

### ISSUE THREAD

**Issue by thenetimp** [SevenBits/Enterprise#34]
I have installed using virtualbox a installation of Ubuntu 14.04 with a few programs not generally available without some custom repos.  I then used a program called respins-gtk to create a custom iso of said system.  I have tested that that iso boots fine in virtual box.  Using Mac USB Linux loader and chose this new iso and added to the enterprise.cfg the following lines to the file.

> entry Custom Linux
> kernel /casper/vmlinuz
> initrd /casper/initrd.gz

When going through the boot process I am able to select the EFI drive, and it accepts both the ekernel and initrd as valid but then it fails the boot process with

    sd 0:0:0:0 [sdb] No caching mode page found
    sd 0:0:0:0 [sdb] Assuming drive cache write through

Reproduction is fairly simple.   Install Ubuntu 14.04 in virtualbox.  Respins-GTK installation instructions are here.   http://respins.org/get.php  In your vm add a couple users, or programs, then run respins-gtk.  Choose "Dist" button then sit back while it makes the imagefile.  Then using "Mac USB Linux Loader" add to a USB stick and set the custom linux parameters above.  Reboot and loading of linux should fail as described.

**Comment by SevenBits** [comment]
@thenetimp Are you first verified that your hardware is compatible with Ubuntu? Did you try using the stock ISOs from Canonical before trying your own?

**Comment by thenetimp** [comment]
Yes.  My mac is March 2015.  I have created been able to use the stock 14.04 image from Ubuntu with no problems.

**Comment by SevenBits** [comment]
@thenetimp Okay then. I haven't used `respins-gtk`, so I can't give too much in the way of specific advice, though it's possible that it modifies the distribution somehow to make Mac Linux USB Loader not work. Booting Linux on EFI (and Macs especially) is a very tricky process indistinguishable from black magic. :)

About the "error" messages you saw, though: none of these is an error message. It's a (rather harmless) message from the kernel. See [this post on Ask Ubuntu][1] for a description of exactly what this message means. I happen to these messages all the time when I boot Linux on my Mac.

This leads to the question, though: why is your custom distribution failing to boot, when the stock Ubuntu ISO boots without issue? Well, there are several possible reasons:

1) do you need to boot with `nomodeset` enabled? On my Mac, this option is required; otherwise you just get a black screen and the system appears to hang.

2) does the system have all drivers installed? Can the kernel read from your USB drive (likely yes, but check just to be sure...)

3) is the version of Ubuntu you're using too old? Perhaps you should try with Ubuntu 15.10.

Please research these questions and let me know the answers.

[1]: https://askubuntu.com/questions/129402/no-caching-mode-page-present-when-usb-flash-disk-attached "Ask Ubuntu"

**Comment by thenetimp** [comment]
After further investigation I agree that it is probably not the Enterprise
software.  When it loads the kernel and the image it seems to load them
without issue and then I see a flicker of x-windows and then it fails.  I
haven't had a chance to look further into this, but it's definitely not an
issue with your software so please close the bug.  I do not have time for
the next couple weeks to dig into this, but will take your suggestion under
advisement.  Thanks again.
